name: 'ReformCloud2SpigotExecutor'
version: '2'
authors: ['_Klaro', 'ReformCloud-Team']
main: de.klaro.reformcloud2.executor.api.spigot.SpigotLauncher

load: STARTUP
# Additional
website: 'https://reformcloud.systems'
description: 'The reformcloud executor api'
